In [447]:
import pandas as pd

In [448]:
evaluations = pd.read_csv("../data/raw/evaluations.csv")
sessions = pd.read_csv("../data/raw/sessions.csv")
model_pricing = pd.read_csv("../data/raw/model_pricing.csv")
llm_calls = pd.read_csv("../data/raw/llm_calls.csv")

# Exploring the llm_calls to see whats wrong with it

In [449]:
df = llm_calls
df.head()

,call_id,session_id,idempotency_key,model,tool_name,prompt_tokens,completion_tokens,cache_hit,latency_ms,status,logged_cost_usd,called_at,attempt_no
0,CL-0012245,SS800566,IK-0012245,mlg-tutor-lg,explain_grammar,1338,239,True,906,success,0.002523,2026-08-08 22:00:00,1
1,CL-0013004,SS802118,IK-0013004,mlg-asr-align,fetch_audio,1328,413,0,1217,context_overflow,0.000243,1767423822,1
2,CL-0026948,SS801086,IK-0012655,mlg-tutor-lg,none,1298,5,1,1127,success,0.001450,2025-12-25 07:14:46,2
3,CL-0008182,SS800963,IK-0008182,mlg-translate-lg,explain_grammar,1018,67,False,1476,tool_error,0.001029,2026-06-20 11:00:58,1
4,CL-0019992,SS804850,IK-0019992,mlg-tutor-sm,none,20,130,1,293,refusal,0.000108,2025-11-15 07:10:09,1

In [450]:
df.describe()

       completion_tokens  logged_cost_usd    attempt_no
count        27854.00000     27160.000000  27854.000000
mean           195.19254         0.000665      1.032311
std            128.71690         0.000710      0.176829
min              5.00000         0.000002      1.000000
25%             98.00000         0.000154      1.000000
50%            187.00000         0.000309      1.000000
75%            283.00000         0.001080      1.000000
max            847.00000         0.004384      2.000000

In [451]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27854 entries, 0 to 27853
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   call_id            27854 non-null  object
 1   session_id         27854 non-null  object
 2   idempotency_key    27854 non-null  object
 3   model              27854 non-null  object
 4   tool_name          27854 non-null  object
 5   prompt_tokens      27854 non-null  object
 6   completion_tokens  27854 non-null  int64
 7   cache_hit          27854 non-null  object
 8   latency_ms         27854 non-null  object
 9   status             27854 non-null  object
 10  logged_cost_usd    27160 non-null  float64
 11  called_at          27854 non-null  object
 12  attempt_no         27854 non-null  int64
dtypes: float64(1), int64(2), object(10)
memory usage: 2.8+ MB

# Dtype errors
-called_at is supposed to be of time date time but its not need to fix that,
-these dtypes objects are supose to be strings

In [452]:
df.isna().sum()

call_id                0
session_id             0
idempotency_key        0
model                  0
tool_name              0
prompt_tokens          0
completion_tokens      0
cache_hit              0
latency_ms             0
status                 0
logged_cost_usd      694
called_at              0
attempt_no             0
dtype: int64

In [453]:
df.head()

,call_id,session_id,idempotency_key,model,tool_name,prompt_tokens,completion_tokens,cache_hit,latency_ms,status,logged_cost_usd,called_at,attempt_no
0,CL-0012245,SS800566,IK-0012245,mlg-tutor-lg,explain_grammar,1338,239,True,906,success,0.002523,2026-08-08 22:00:00,1
1,CL-0013004,SS802118,IK-0013004,mlg-asr-align,fetch_audio,1328,413,0,1217,context_overflow,0.000243,1767423822,1
2,CL-0026948,SS801086,IK-0012655,mlg-tutor-lg,none,1298,5,1,1127,success,0.001450,2025-12-25 07:14:46,2
3,CL-0008182,SS800963,IK-0008182,mlg-translate-lg,explain_grammar,1018,67,False,1476,tool_error,0.001029,2026-06-20 11:00:58,1
4,CL-0019992,SS804850,IK-0019992,mlg-tutor-sm,none,20,130,1,293,refusal,0.000108,2025-11-15 07:10:09,1

In [454]:
# df.model.value_counts()

# def value_count(column):
#     print(column.value_counts())

# df.drop(columns=["prompt_tokens", "completion_tokens", "logged_cost_usd"]).apply(value_count)

In [455]:
print(df.dtypes)
df.head()
df.tail()

call_id               object
session_id            object
idempotency_key       object
model                 object
tool_name             object
prompt_tokens         object
completion_tokens      int64
cache_hit             object
latency_ms            object
status                object
logged_cost_usd      float64
called_at             object
attempt_no             int64
dtype: object

,call_id,session_id,idempotency_key,model,tool_name,prompt_tokens,completion_tokens,cache_hit,latency_ms,status,logged_cost_usd,called_at,attempt_no
27849,CL-0017641,SS800659,IK-0017641,mlg-asr-align,none,928,322,False,998,success,0.000180,2026-02-21 22:08:24,1
27850,CL-0023967,SS804204,IK-0023967,mlg-tutor-sm,lookup_dictionary,1138,170,False,646,success,0.000262,2026-01-30 12:03:06,1
27851,CL-0010532,SS801424,IK-0010532,mlg-translate-sm,none,834,248,no,160,success,0.000274,20/06/2026 09:11,1
27852,CL-0006531,SS801501,IK-0006531,mlg-tutor-lg,none,108,216,0,5625,timeout,0.001069,2026-06-12 11:00:00,1
27853,CL-0015791,SS801009,IK-0015791,mlg-translate-lg,lookup_dictionary,394,211,False,702,tool_error,0.000989,2026-01-12 15:00:33,1

# Fix column data type and value anomalies

In [456]:
from decimal import Decimal

In [457]:
numeric_cols = ["prompt_tokens", "completion_tokens", "logged_cost_usd", "attempt_no", "latency_ms"]
string_cols = df.drop(columns=numeric_cols+["called_at", "cache_hit"]).columns.tolist()
boolean_map = {
    True: True,   False:False,
    "True": True, "False":False,
    "TRUE": True,  "FALSE": False,
    "1"   : True,  "0": False,
    "yes" : True,  "no": False,
    1      : True, 0:False
}
print(string_cols)
def convert_to_int(column):
    #convert all numeric columns to numeric data

    if column.name in numeric_cols:
        #split latency text to remove "ms from it"
        if column.name == "latency_ms":
            column = column.apply(lambda x: x.split(" ")[0])
        if column.name == "prompt_tokens":
            column = column.apply(lambda x: int(x.replace(",","")))
        try:
            return column.apply(lambda x: Decimal(str(x)) if pd.notna(x) else x)
        except:
            return 

    # resolve model naming conflict wiht capitalisation issues , and
    if column.name in string_cols:
        # first bring all model names to lowercase 
        if column.name == "model":
            column = column.apply(lambda x: x.lower())
        return column.astype("string")

    # handle boolean values
    if column.name == "cache_hit":
        return column.map(boolean_map)
    return column

['call_id', 'session_id', 'idempotency_key', 'model', 'tool_name', 'status']

realised latency ms has some values with "ms" string ttacehd to it so cannot convert to numeric

In [458]:
df= df.apply(convert_to_int)
df.dtypes

call_id              string[python]
session_id           string[python]
idempotency_key      string[python]
model                string[python]
tool_name            string[python]
prompt_tokens                object
completion_tokens            object
cache_hit                      bool
latency_ms                   object
status               string[python]
logged_cost_usd              object
called_at                    object
attempt_no                   object
dtype: object

In [459]:
df.head()

,call_id,session_id,idempotency_key,model,tool_name,prompt_tokens,completion_tokens,cache_hit,latency_ms,status,logged_cost_usd,called_at,attempt_no
0,CL-0012245,SS800566,IK-0012245,mlg-tutor-lg,explain_grammar,1338,239,True,906,success,0.0025234,2026-08-08 22:00:00,1
1,CL-0013004,SS802118,IK-0013004,mlg-asr-align,fetch_audio,1328,413,False,1217,context_overflow,0.000243435,1767423822,1
2,CL-0026948,SS801086,IK-0012655,mlg-tutor-lg,none,1298,5,True,1127,success,0.0014498,2025-12-25 07:14:46,2
3,CL-0008182,SS800963,IK-0008182,mlg-translate-lg,explain_grammar,1018,67,False,1476,tool_error,0.001028889,2026-06-20 11:00:58,1
4,CL-0019992,SS804850,IK-0019992,mlg-tutor-sm,none,20,130,True,293,refusal,0.000107957,2025-11-15 07:10:09,1

In [460]:
df.isna().sum()

call_id                0
session_id             0
idempotency_key        0
model                  0
tool_name              0
prompt_tokens          0
completion_tokens      0
cache_hit              0
latency_ms             0
status                 0
logged_cost_usd      694
called_at              0
attempt_no             0
dtype: int64

In [461]:
df.prompt_tokens.apply(lambda x: type(x)).value_counts()

prompt_tokens
<class 'decimal.Decimal'>    27854
Name: count, dtype: int64

In [462]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27854 entries, 0 to 27853
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   call_id            27854 non-null  string
 1   session_id         27854 non-null  string
 2   idempotency_key    27854 non-null  string
 3   model              27854 non-null  string
 4   tool_name          27854 non-null  string
 5   prompt_tokens      27854 non-null  object
 6   completion_tokens  27854 non-null  object
 7   cache_hit          27854 non-null  bool
 8   latency_ms         27854 non-null  object
 9   status             27854 non-null  string
 10  logged_cost_usd    27160 non-null  object
 11  called_at          27854 non-null  object
 12  attempt_no         27854 non-null  object
dtypes: bool(1), object(6), string(6)
memory usage: 2.6+ MB

There are missing telimetry values for logged_cost