In [135]:
import pandas as pd

In [136]:
evaluations = pd.read_csv("../data/raw/evaluations.csv")
sessions = pd.read_csv("../data/raw/sessions.csv")
model_pricing = pd.read_csv("../data/raw/model_pricing.csv")
llm_calls = pd.read_csv("../data/raw/llm_calls.csv")

# Exploring the llm_calls to see whats wrong with it

In [137]:
df = llm_calls
df.head()

,call_id,session_id,idempotency_key,model,tool_name,prompt_tokens,completion_tokens,cache_hit,latency_ms,status,logged_cost_usd,called_at,attempt_no
0,CL-0012245,SS800566,IK-0012245,mlg-tutor-lg,explain_grammar,1338,239,True,906,success,0.002523,2026-08-08 22:00:00,1
1,CL-0013004,SS802118,IK-0013004,mlg-asr-align,fetch_audio,1328,413,0,1217,context_overflow,0.000243,1767423822,1
2,CL-0026948,SS801086,IK-0012655,mlg-tutor-lg,none,1298,5,1,1127,success,0.001450,2025-12-25 07:14:46,2
3,CL-0008182,SS800963,IK-0008182,mlg-translate-lg,explain_grammar,1018,67,False,1476,tool_error,0.001029,2026-06-20 11:00:58,1
4,CL-0019992,SS804850,IK-0019992,mlg-tutor-sm,none,20,130,1,293,refusal,0.000108,2025-11-15 07:10:09,1

In [138]:
df.describe()

       completion_tokens  logged_cost_usd    attempt_no
count        27854.00000     27160.000000  27854.000000
mean           195.19254         0.000665      1.032311
std            128.71690         0.000710      0.176829
min              5.00000         0.000002      1.000000
25%             98.00000         0.000154      1.000000
50%            187.00000         0.000309      1.000000
75%            283.00000         0.001080      1.000000
max            847.00000         0.004384      2.000000

In [139]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27854 entries, 0 to 27853
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   call_id            27854 non-null  object
 1   session_id         27854 non-null  object
 2   idempotency_key    27854 non-null  object
 3   model              27854 non-null  object
 4   tool_name          27854 non-null  object
 5   prompt_tokens      27854 non-null  object
 6   completion_tokens  27854 non-null  int64
 7   cache_hit          27854 non-null  object
 8   latency_ms         27854 non-null  object
 9   status             27854 non-null  object
 10  logged_cost_usd    27160 non-null  float64
 11  called_at          27854 non-null  object
 12  attempt_no         27854 non-null  int64
dtypes: float64(1), int64(2), object(10)
memory usage: 2.8+ MB

# Dtype errors
-called_at is supposed to be of time date time but its not need to fix that,
-these dtypes objects are supose to be strings

In [140]:
df.isna().sum()

call_id                0
session_id             0
idempotency_key        0
model                  0
tool_name              0
prompt_tokens          0
completion_tokens      0
cache_hit              0
latency_ms             0
status                 0
logged_cost_usd      694
called_at              0
attempt_no             0
dtype: int64

In [141]:
df.head()

,call_id,session_id,idempotency_key,model,tool_name,prompt_tokens,completion_tokens,cache_hit,latency_ms,status,logged_cost_usd,called_at,attempt_no
0,CL-0012245,SS800566,IK-0012245,mlg-tutor-lg,explain_grammar,1338,239,True,906,success,0.002523,2026-08-08 22:00:00,1
1,CL-0013004,SS802118,IK-0013004,mlg-asr-align,fetch_audio,1328,413,0,1217,context_overflow,0.000243,1767423822,1
2,CL-0026948,SS801086,IK-0012655,mlg-tutor-lg,none,1298,5,1,1127,success,0.001450,2025-12-25 07:14:46,2
3,CL-0008182,SS800963,IK-0008182,mlg-translate-lg,explain_grammar,1018,67,False,1476,tool_error,0.001029,2026-06-20 11:00:58,1
4,CL-0019992,SS804850,IK-0019992,mlg-tutor-sm,none,20,130,1,293,refusal,0.000108,2025-11-15 07:10:09,1

In [142]:
# df.model.value_counts()

# def value_count(column):
#     print(column.value_counts())

# df.drop(columns=["prompt_tokens", "completion_tokens", "logged_cost_usd"]).apply(value_count)

In [143]:
print(df.dtypes)
df.head()
df.tail()

call_id               object
session_id            object
idempotency_key       object
model                 object
tool_name             object
prompt_tokens         object
completion_tokens      int64
cache_hit             object
latency_ms            object
status                object
logged_cost_usd      float64
called_at             object
attempt_no             int64
dtype: object

,call_id,session_id,idempotency_key,model,tool_name,prompt_tokens,completion_tokens,cache_hit,latency_ms,status,logged_cost_usd,called_at,attempt_no
27849,CL-0017641,SS800659,IK-0017641,mlg-asr-align,none,928,322,False,998,success,0.000180,2026-02-21 22:08:24,1
27850,CL-0023967,SS804204,IK-0023967,mlg-tutor-sm,lookup_dictionary,1138,170,False,646,success,0.000262,2026-01-30 12:03:06,1
27851,CL-0010532,SS801424,IK-0010532,mlg-translate-sm,none,834,248,no,160,success,0.000274,20/06/2026 09:11,1
27852,CL-0006531,SS801501,IK-0006531,mlg-tutor-lg,none,108,216,0,5625,timeout,0.001069,2026-06-12 11:00:00,1
27853,CL-0015791,SS801009,IK-0015791,mlg-translate-lg,lookup_dictionary,394,211,False,702,tool_error,0.000989,2026-01-12 15:00:33,1

# Fix column data type and value anomalies

In [144]:
from decimal import Decimal

In [145]:
numeric_cols = ["prompt_tokens", "completion_tokens", "logged_cost_usd", "attempt_no", "latency_ms"]
string_cols = df.drop(columns=numeric_cols+["called_at", "cache_hit"]).columns.tolist()
boolean_map = {
    True: True,   False:False,
    "True": True, "False":False,
    "TRUE": True,  "FALSE": False,
    "1"   : True,  "0": False,
    "yes" : True,  "no": False,
    1      : True, 0:False
}

def convert_date_time(column):
    try:
        return pd.to_datetime(column, format="mixed")
    except:
        return pd.to_datetime(column,unit="s")
    

def convert_to_int(column):
    #convert all numeric columns to numeric data

    if column.name in numeric_cols:
        #split latency text to remove "ms from it"
        if column.name == "latency_ms":
            column = column.apply(lambda x: x.split(" ")[0])
        if column.name == "prompt_tokens":
            column = column.apply(lambda x: int(x.replace(",","")))
        try:
            return column.apply(lambda x: Decimal(str(x)) if pd.notna(x) else x)
        except:
            return 

    # resolve model naming conflict wiht capitalisation issues , and
    if column.name in string_cols:
        # first bring all model names to lowercase 
        if column.name == "model":
            column = column.apply(lambda x: x.lower())
        return column.astype("string")

    # handle boolean values
    if column.name == "cache_hit":
        return column.map(boolean_map)

    return column

realised latency ms has some values with "ms" string ttacehd to it so cannot convert to numeric

In [146]:
df= df.apply(convert_to_int)
df["called_at"] = df.called_at.apply(convert_date_time)
df.dtypes

C:\Users\chris\AppData\Local\Temp\ipykernel_16668\3562644243.py:16: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  return pd.to_datetime(column,unit="s")

call_id              string[python]
session_id           string[python]
idempotency_key      string[python]
model                string[python]
tool_name            string[python]
prompt_tokens                object
completion_tokens            object
cache_hit                      bool
latency_ms                   object
status               string[python]
logged_cost_usd              object
called_at            datetime64[ns]
attempt_no                   object
dtype: object

In [147]:
df.head()

,call_id,session_id,idempotency_key,model,tool_name,prompt_tokens,completion_tokens,cache_hit,latency_ms,status,logged_cost_usd,called_at,attempt_no
0,CL-0012245,SS800566,IK-0012245,mlg-tutor-lg,explain_grammar,1338,239,True,906,success,0.0025234,2026-08-08 22:00:00,1
1,CL-0013004,SS802118,IK-0013004,mlg-asr-align,fetch_audio,1328,413,False,1217,context_overflow,0.000243435,2026-01-03 07:03:42,1
2,CL-0026948,SS801086,IK-0012655,mlg-tutor-lg,none,1298,5,True,1127,success,0.0014498,2025-12-25 07:14:46,2
3,CL-0008182,SS800963,IK-0008182,mlg-translate-lg,explain_grammar,1018,67,False,1476,tool_error,0.001028889,2026-06-20 11:00:58,1
4,CL-0019992,SS804850,IK-0019992,mlg-tutor-sm,none,20,130,True,293,refusal,0.000107957,2025-11-15 07:10:09,1

In [148]:
df.isna().sum()

call_id                0
session_id             0
idempotency_key        0
model                  0
tool_name              0
prompt_tokens          0
completion_tokens      0
cache_hit              0
latency_ms             0
status                 0
logged_cost_usd      694
called_at              0
attempt_no             0
dtype: int64

There are missing telimetry values for logged_cost

In [149]:
df.to_csv("../data/cleaned/llm_calls.csv")

In [150]:
df = sessions
df.head()

,session_id,user_id,app_version,device,locale,plan,started_at,network
0,SS805137,US100303,3.3.0,android,ara,free,2026-03-16 19:00:00,offline-sync
1,SS803773,US100724,3.3.1,android,amh,free,2025-12-20 11:00:00,2g
2,SS802937,US102254,3.2.0,android,zul,free,2026-06-26 06:00:00,wifi
3,SS800313,US100541,3.3.0,IOS,fra,premium,2026-04-04 09:00:00,4g
4,SS802055,US100211,3.1.1,android,ibo,Premium,2026-01-05 14:00:00,offline-sync

In [151]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5260 entries, 0 to 5259
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   session_id   5260 non-null   object
 1   user_id      5260 non-null   object
 2   app_version  5260 non-null   object
 3   device       5260 non-null   object
 4   locale       5260 non-null   object
 5   plan         5260 non-null   object
 6   started_at   5260 non-null   object
 7   network      5260 non-null   object
dtypes: object(8)
memory usage: 328.9+ KB

In [152]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
5255    False
5256    False
5257    False
5258    False
5259     True
Length: 5260, dtype: bool

session table has duplicate columns

In [153]:
for idx, i in df.duplicated().items():
    print(i)
    if i:
        print(df.loc[idx])

False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
True
session_id                SS804861
user_id                   US101417
app_version                  3.3.1
device                     android
locale                         hau
plan                          free
started_at     2025-11-27 15:00:00
network                         3g
Name: 1294, dtype: object
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
True
session_id                SS803710
user_id                   US100578
app_version                  3.1.1
device                         ios
locale                         ara
plan                          free
started_at     2026-07-12 14:00:00
network                         3g
Name: 2270, dtype: object
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
True
session_id                SS801540
user_id                   US100590
app_version                  3.3.1
device                     android
locale                         swa
plan                          free
started_at     2026-05-04 09:00:00
network                         4g
Name: 2395, dtype: object
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
True
session_id                SS803835
user_id                   US102175
app_version                  3.2.1
device                     android
locale                         eng
plan                          free
started_at     2026-07-16 15:00:00
network                         4g
Name: 2700, dtype: object
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
True
session_id                SS801951
user_id                   US100599
app_version                  3.3.0
device                     android
locale                         lin
plan                          free
started_at     2026-06-15 15:00:00
network                       wifi
Name: 2768, dtype: object
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False

In [154]:
df

,session_id,user_id,app_version,device,locale,plan,started_at,network
0,SS805137,US100303,3.3.0,android,ara,free,2026-03-16 19:00:00,offline-sync
1,SS803773,US100724,3.3.1,android,amh,free,2025-12-20 11:00:00,2g
2,SS802937,US102254,3.2.0,android,zul,free,2026-06-26 06:00:00,wifi
3,SS800313,US100541,3.3.0,IOS,fra,premium,2026-04-04 09:00:00,4g
4,SS802055,US100211,3.1.1,android,ibo,Premium,2026-01-05 14:00:00,offline-sync
...,...,...,...,...,...,...,...,...
5255,SS804201,US101649,3.3.1,android,som,trial,1777489200,3g
5256,SS800212,US100398,3.1.1,IOS,swa,Premium,2026-06-10 20:00:00,4g
5257,SS801572,US102040,3.2.1,ios,por,free,2026-01-26 13:00:00,2g
5258,SS801664,US102082,3.1.0,android,swa,free,1765576800,4g
5259,SS803455,US101319,3.1.0,android,som,free,2026-01-18 22:00:00,2g

In [155]:
df1 = pd.read_csv("../data/cleaned/llm_calls.csv")
df2 = model_pricing

In [156]:
df2

,model,prompt_usd_per_token,completion_usd_per_token,effective_from
0,mlg-translate-sm,1.500000e-07,6.000000e-07,2025-11-01
1,mlg-translate-lg,8.000000e-07,3.200000e-06,2025-11-01
2,mlg-tutor-sm,2.000000e-07,8.000000e-07,2025-11-01
3,mlg-tutor-lg,1.100000e-06,4.400000e-06,2025-11-01
4,mlg-asr-align,9.000000e-08,3.000000e-07,2025-11-01

In [157]:
df1.head()

,Unnamed: 0,call_id,session_id,idempotency_key,model,tool_name,prompt_tokens,completion_tokens,cache_hit,latency_ms,status,logged_cost_usd,called_at,attempt_no
0,0,CL-0012245,SS800566,IK-0012245,mlg-tutor-lg,explain_grammar,1338,239,True,906,success,0.002523,2026-08-08 22:00:00,1
1,1,CL-0013004,SS802118,IK-0013004,mlg-asr-align,fetch_audio,1328,413,False,1217,context_overflow,0.000243,2026-01-03 07:03:42,1
2,2,CL-0026948,SS801086,IK-0012655,mlg-tutor-lg,none,1298,5,True,1127,success,0.001450,2025-12-25 07:14:46,2
3,3,CL-0008182,SS800963,IK-0008182,mlg-translate-lg,explain_grammar,1018,67,False,1476,tool_error,0.001029,2026-06-20 11:00:58,1
4,4,CL-0019992,SS804850,IK-0019992,mlg-tutor-sm,none,20,130,True,293,refusal,0.000108,2025-11-15 07:10:09,1

In [ ]:
def get_model_completion_cost(model):
    return df2.query(f"model == '{model}'").completion_usd_per_token.values

def calculate_actual_cost(model, completion_tokens, cache_status=False)-> Decimal:
    token_price = get_model_completion_cost(model)
    if cache_status:
        return Decimal(0)
    return (Decimal(completion_tokens)*Decimal(token_price))

In [ ]:
# df1["actual_cost"] = df1.apply(lambda x: ))

SyntaxError: unmatched ')' (3020725849.py, line 1)

In [160]:
get_model_completion_cost("mlg-tutor-lg")

3    0.000004
Name: completion_usd_per_token, dtype: float64